Teab/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('dashboard/', include('dashboard.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path
from . import views


app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('email/', views.email, name='email'),
    path('login/', views.login, name='login'),
    path('media/', views.media, name='media'),
    path('profile/', views.profile, name='profile'),
    path('tables/', views.tables, name='tables'),

    path('banner_delete/', views.banner_delete, name='banner_delete'),
    path('banner_details/', views.banner_details, name='banner_details'),
    path('banner_form/', views.banner_form, name='banner_form'),
    path('banner_list/', views.banner_list, name='banner_list'),

    path('faq_delete/', views.faq_delete, name='faq_delete'),
    path('faq_details/', views.faq_details, name='faq_details'),
    path('faq_form/', views.faq_form, name='faq_form'),
    path('faq_list/', views.faq_list, name='faq_list'),

    path('product_delete/', views.product_delete, name='product_delete'),
    path('product_details/', views.product_details, name='product_details'),
    path('product_form/', views.product_form, name='product_form'),
    path('product_list/', views.product_list, name='product_list'),

    path('testimonial_delete/', views.testimonial_delete, name='testimonial_delete'),
    path('testimonial_details/', views.testimonial_details, name='testimonial_details'),
    path('testimonial_form/', views.testimonial_form, name='testimonial_form'),
    path('testimonial_list/', views.testimonial_list, name='testimonial_list'),
]

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
from django.shortcuts import render
from .decorator import decorator


def index(request):
    return render(request, 'dashboard/index.html')

def contact(request):
    return render(request, 'dashboard/contact.html')

def email(request):
    return render(request, 'dashboard/email.html')

def login(request):
    return render(request, 'dashboard/login.html')

def media(request):
    return render(request, 'dashboard/media_gallery.html')

def profile(request):
    return render(request, 'dashboard/profile.html')

def tables(request):
    return render(request, 'dashboard/tables.html')

'''CRUD'''

def banner_delete(request):
    return render(request, 'back-office/banner/delete.html')

def banner_details(request):
    return render(request, 'back-office/banner/details.html')

def banner_form(request):
    return render(request, 'back-office/banner/form.html')

def banner_list(request):
    return render(request, 'back-office/banner/list.html')

def faq_delete(request):
    return render(request, 'back-office/faq/delete.html')

def faq_details(request):
    return render(request, 'back-office/faq/details.html')

def faq_form(request):
    return render(request, 'back-office/faq/form.html')

def faq_list(request):
    return render(request, 'back-office/faq/list.html')

def product_delete(request):
    return render(request, 'back-office/product/delete.html')

def product_details(request):
    return render(request, 'back-office/product/details.html')

def product_form(request):
    return render(request, 'back-office/product/form.html')

def product_list(request):
    return render(request, 'back-office/product/list.html')

def testimonial_delete(request):
    return render(request, 'back-office/testimonial/delete.html')

def testimonial_details(request):
    return render(request, 'back-office/testimonial/details.html')

def testimonial_form(request):
    return render(request, 'back-office/testimonial/form.html')

def testimonial_list(request):
    return render(request, 'back-office/testimonial/list.html')

templates/dashboard/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
   <head>
      <!-- basic -->
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <!-- mobile metas -->
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="viewport" content="initial-scale=1, maximum-scale=1">
      <!-- site metas -->
      <title>Pluto - Responsive Bootstrap Admin Panel Templates</title>
      <meta name="keywords" content="">
      <meta name="description" content="">
      <meta name="author" content="">
      <!-- site icon -->
      <link rel="icon" href="{% static 'images/fevicon.png' %}" type="image/png" />
      <!-- bootstrap css -->
      <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
      <!-- site css -->
      <link rel="stylesheet" href="{% static 'style.css' %}" />
      <!-- responsive css -->
      <link rel="stylesheet" href="{% static 'css/responsive.css' %}" />
      <!-- color css -->
      <link rel="stylesheet" href="{% static 'css/colors.css' %}" />
      <!-- select bootstrap -->
      <link rel="stylesheet" href="{% static 'css/bootstrap-select.css' %}" />
      <!-- scrollbar css -->
      <link rel="stylesheet" href="{% static 'css/perfect-scrollbar.css' %}" />
      <!-- custom css -->
      <link rel="stylesheet" href="{% static 'css/custom.css' %}" />
      <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
      <![endif]-->
   </head>
   <body class="dashboard dashboard_1">
      <div class="full_container">
         <div class="inner_container">
            <!-- Sidebar  -->
            <nav id="sidebar">
               <div class="sidebar_blog_1">
                  <div class="sidebar-header">
                     <div class="logo_section">
                        <a href="index.html"><img class="logo_icon img-responsive" src="images/logo/logo_icon.png" alt="#" /></a>
                     </div>
                  </div>
                  <div class="sidebar_user_info">
                     <div class="icon_setting"></div>
                     <div class="user_profle_side">
                        <div class="user_img"><img class="img-responsive" src="images/layout_img/user_img.jpg" alt="#" /></div>
                        <div class="user_info">
                           <h6>John David</h6>
                           <p><span class="online_animation"></span> Online</p>
                        </div>
                     </div>
                  </div>
               </div>
               <div class="sidebar_blog_2">
                  <h4>General</h4>
                  <ul class="list-unstyled components">
                     <li class="active">
                        <a href="#dashboard" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle"><i class="fa fa-dashboard yellow_color"></i> <span>Dashboard</span></a>
                        <ul class="collapse list-unstyled" id="dashboard">
                           <li>
                              <a href="index.html">> <span>Default Dashboard</span></a>
                           </li>
                        </ul>
                     </li>
                     <li><a href="widgets.html"><i class="fa fa-clock-o orange_color"></i> <span>Widgets</span></a></li>
                     <li>
                        <a href="#element" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle"><i class="fa fa-diamond purple_color"></i> <span>Elements</span></a>
                        <ul class="collapse list-unstyled" id="element">
                           <li><a href="general_elements.html">> <span>General Elements</span></a></li>
                           <li><a href="media_gallery.html">> <span>Media Gallery</span></a></li>
                           <li><a href="icons.html">> <span>Icons</span></a></li>
                           <li><a href="invoice.html">> <span>Invoice</span></a></li>
                        </ul>
                     </li>
                     <li><a href="tables.html"><i class="fa fa-table purple_color2"></i> <span>Tables</span></a></li>
                     <li>
                        <a href="#apps" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle"><i class="fa fa-object-group blue2_color"></i> <span>Apps</span></a>
                        <ul class="collapse list-unstyled" id="apps">
                           <li><a href="email.html">> <span>Email</span></a></li>
                           <li><a href="calendar.html">> <span>Calendar</span></a></li>
                           <li><a href="media_gallery.html">> <span>Media Gallery</span></a></li>
                        </ul>
                     </li>
                     <li><a href="price.html"><i class="fa fa-briefcase blue1_color"></i> <span>Pricing Tables</span></a></li>
                     <li>
                        <a href="contact.html">
                        <i class="fa fa-paper-plane red_color"></i> <span>Contact</span></a>
                     </li>
                     <li class="active">
                        <a href="#additional_page" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle"><i class="fa fa-clone yellow_color"></i> <span>Additional Pages</span></a>
                        <ul class="collapse list-unstyled" id="additional_page">
                           <li>
                              <a href="profile.html">> <span>Profile</span></a>
                           </li>
                           <li>
                              <a href="project.html">> <span>Projects</span></a>
                           </li>
                           <li>
                              <a href="login.html">> <span>Login</span></a>
                           </li>
                           <li>
                              <a href="404_error.html">> <span>404 Error</span></a>
                           </li>
                        </ul>
                     </li>
                     <li><a href="map.html"><i class="fa fa-map purple_color2"></i> <span>Map</span></a></li>
                     <li><a href="charts.html"><i class="fa fa-bar-chart-o green_color"></i> <span>Charts</span></a></li>
                     <li><a href="settings.html"><i class="fa fa-cog yellow_color"></i> <span>Settings</span></a></li>
                  </ul>
               </div>
            </nav>
            <!-- end sidebar -->
            <!-- right content -->
            <div id="content">
               <!-- topbar -->
               <div class="topbar">
                  <nav class="navbar navbar-expand-lg navbar-light">
                     <div class="full">
                        <button type="button" id="sidebarCollapse" class="sidebar_toggle"><i class="fa fa-bars"></i></button>
                        <div class="logo_section">
                           <a href="index.html"><img class="img-responsive" src="images/logo/logo.png" alt="#" /></a>
                        </div>
                        <div class="right_topbar">
                           <div class="icon_info">
                              <ul>
                                 <li><a href="#"><i class="fa fa-bell-o"></i><span class="badge">2</span></a></li>
                                 <li><a href="#"><i class="fa fa-question-circle"></i></a></li>
                                 <li><a href="#"><i class="fa fa-envelope-o"></i><span class="badge">3</span></a></li>
                              </ul>
                              <ul class="user_profile_dd">
                                 <li>
                                    <a class="dropdown-toggle" data-toggle="dropdown"><img class="img-responsive rounded-circle" src="images/layout_img/user_img.jpg" alt="#" /><span class="name_user">John David</span></a>
                                    <div class="dropdown-menu">
                                       <a class="dropdown-item" href="profile.html">My Profile</a>
                                       <a class="dropdown-item" href="settings.html">Settings</a>
                                       <a class="dropdown-item" href="help.html">Help</a>
                                       <a class="dropdown-item" href="#"><span>Log Out</span> <i class="fa fa-sign-out"></i></a>
                                    </div>
                                 </li>
                              </ul>
                           </div>
                        </div>
                     </div>
                  </nav>
               </div>
               <!-- end topbar -->
               <!-- dashboard inner -->
               <div class="midde_cont">
                    
                    {% block content %}

                    {% endblock %}

                  <!-- footer -->
                  <div class="container-fluid">
                     <div class="footer">
                        <p>Copyright © 2018 Designed by html.design. All rights reserved.<br><br>
                           Distributed By: <a href="https://themewagon.com/">ThemeWagon</a>
                        </p>
                     </div>
                  </div>
               </div>
               <!-- end dashboard inner -->
            </div>
         </div>
      </div>
      <!-- jQuery -->
      <script src="{% static 'js/jquery.min.js' %}"></script>
      <script src="{% static 'js/popper.min.js' %}"></script>
      <script src="{% static 'js/bootstrap.min.js' %}"></script>
      <!-- wow animation -->
      <script src="{% static 'js/animate.js' %}"></script>
      <!-- select country -->
      <script src="{% static 'js/bootstrap-select.js' %}"></script>
      <!-- owl carousel -->
      <script src="{% static 'js/owl.carousel.js' %}"></script> 
      <!-- chart js -->
      <script src="{% static 'js/Chart.min.js' %}"></script>
      <script src="{% static 'js/Chart.bundle.min.js' %}"></script>
      <script src="{% static 'js/utils.js' %}"></script>
      <script src="{% static 'js/analyser.js' %}"></script>
      <!-- nice scrollbar -->
      <script src="{% static 'js/perfect-scrollbar.min.js' %}"></script>
      <script>
         var ps = new PerfectScrollbar('#sidebar');
      </script>
      <!-- custom js -->
      <script src="{% static 'js/custom.js' %}"></script>
      <script src="{% static 'js/chart_custom_style1.js' %}"></script>
   </body>
</html>

templates/dashboard/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
   <head>
      <!-- basic -->
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <!-- mobile metas -->
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="viewport" content="initial-scale=1, maximum-scale=1">
      <!-- site metas -->
      <title>Pluto - Responsive Bootstrap Admin Panel Templates</title>
      <meta name="keywords" content="">
      <meta name="description" content="">
      <meta name="author" content="">
      <!-- site icon -->
      <link rel="icon" href="{% static 'dashboard/images/fevicon.png' %}" type="image/png" />
      <!-- bootstrap css -->
      <link rel="stylesheet" href="{% static 'dashboard/css/bootstrap.min.css' %}" />
      <!-- site css -->
      <link rel="stylesheet" href="{% static 'dashboard/style.css' %}" />
      <!-- responsive css -->
      <link rel="stylesheet" href="{% static 'dashboard/css/responsive.css' %}" />
      <!-- color css -->
      <link rel="stylesheet" href="{% static 'dashboard/css/colors.css' %}" />
      <!-- select bootstrap -->
      <link rel="stylesheet" href="{% static 'dashboard/css/bootstrap-select.css' %}" />
      <!-- scrollbar css -->
      <link rel="stylesheet" href="{% static 'dashboard/css/perfect-scrollbar.css' %}" />
      <!-- custom css -->
      <link rel="stylesheet" href="{% static 'dashboard/css/custom.css' %}" />
      <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
      <![endif]-->
   </head>
   <body class="inner_page login">
      <div class="full_container">
         <div class="container">
            <div class="center verticle_center full_height">
               <div class="login_section">
                  <div class="logo_login">
                     <div class="center">
                        <img width="210" src="{% static 'dashboard/images/logo/logo.png' %}" alt="#" />
                     </div>
                  </div>
                  <div class="login_form">
                     <form>
                        <fieldset>
                           <div class="field">
                              <label class="label_field">Name</label>
                              <input type="text" name="name" placeholder="name" />
                           </div>
                           <div class="field">
                              <label class="label_field">Password</label>
                              <input type="password" name="password" placeholder="password" />
                           </div>
                           <div class="field">
                              <label class="label_field hidden">hidden label</label>
                              <label class="form-check-label"><input type="checkbox" class="form-check-input"> Remember Me</label>
                           </div>
                           <div class="field margin_0">
                              <label class="label_field hidden">hidden label</label>
                              <button class="main_bt">Sing In</button>
                           </div>
                        </fieldset>
                     </form>
                  </div>
               </div>
            </div>
         </div>
      </div>
      <!-- jQuery -->
      <script src="{% static 'dashboard/js/jquery.min.js' %}"></script>
      <script src="{% static 'dashboard/js/popper.min.js' %}"></script>
      <script src="{% static 'dashboard/js/bootstrap.min.js' %}"></script>
      <!-- wow animation -->
      <script src="{% static 'dashboard/js/animate.js' %}"></script>
      <!-- select country -->
      <script src="{% static 'dashboard/js/bootstrap-select.js' %}"></script>
      <!-- nice scrollbar -->
      <script src="{% static 'dashboard/js/perfect-scrollbar.min.js' %}"></script>
      <script>
         var ps = new PerfectScrollbar('#sidebar');
      </script>
      <!-- custom js -->
      <script src="{% static 'dashboard/js/custom.js' %}"></script>
   </body>
</html>

templates/dashboard/media_gallery.html
{% extends 'based.html' %}

{% block content %}
{% load static %}

<div class="container-fluid">
   <div class="row column_title">
      <div class="col-md-12">
         <div class="page_title">
            <h2>Media Gallery</h2>
         </div>
      </div>
   </div>
   <!-- row -->
   <div class="row column4 graph">
      <!-- Gallery section -->
      <div class="col-md-12">
         <div class="white_shd full margin_bottom_30">
            <div class="full graph_head">
               <div class="heading1 margin_0">
                  <h2>Media Gallery Design Elements</h2>
               </div>
            </div>
            <div class="full gallery_section_inner padding_infor_info">
               <div class="row">
                  <div class="col-sm-4 col-md-3 margin_bottom_30">
                     <div class="column">
                        <a data-fancybox="gallery" href="{% static 'dashboard/images/layout_img/g1.jpg' %}"><img class="img-responsive" src="{% static 'dashboard/images/layout_img/g1.jpg' %}" alt="#" /></a>
                     </div>
                     <div class="heading_section">
                        <h4>Sed ut perspiciatis</h4>
                     </div>
                  </div>
                  <div class="col-sm-4 col-md-3 margin_bottom_30">
                     <div class="column">
                        <a data-fancybox="gallery" href="{% static 'dashboard/images/layout_img/g2.jpg' %}"><img class="img-responsive" src="{% static 'dashboard/images/layout_img/g2.jpg' %}" alt="#" /></a>
                     </div>
                     <div class="heading_section">
                        <h4>Sed ut perspiciatis</h4>
                     </div>
                  </div>
                  <div class="col-sm-4 col-md-3 margin_bottom_30">
                     <div class="column">
                        <a data-fancybox="gallery" href="{% static 'dashboard/images/layout_img/g3.jpg' %}"><img class="img-responsive" src="{% static 'dashboard/images/layout_img/g3.jpg' %}" alt="#" /></a>
                     </div>
                     <div class="heading_section">
                        <h4>Sed ut perspiciatis</h4>
                     </div>
                  </div>
                     <div class="column">
                        <a data-fancybox="gallery" href="images/layout_img/g16.jpg"><img class="img-responsive" src="images/layout_img/g16.jpg" alt="#" /></a>
                     </div>
                     <div class="heading_section">
                        <h4>Sed ut perspiciatis</h4>
                     </div>

               </div>
            </div>
         </div>
      </div>
   </div>
   <!-- footer -->
</div>

{% endblock %}

templates/dashboard/profile.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
   <head>
      <!-- basic -->
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <!-- mobile metas -->
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="viewport" content="initial-scale=1, maximum-scale=1">
      <!-- site metas -->
      <title>Pluto - Responsive Bootstrap Admin Panel Templates</title>
      <meta name="keywords" content="">
      <meta name="description" content="">
      <meta name="author" content="">
      <!-- site icon -->
      <link rel="icon" href="{% static 'dashboard/images/fevicon.png' %}" type="image/png" />
      <!-- bootstrap css -->
      <link rel="stylesheet" href="{% static 'dashboard/css/bootstrap.min.css' %}" />
      <!-- site css -->
      <link rel="stylesheet" href="{% static 'dashboard/style.css' %}" />
      <!-- responsive css -->
      <link rel="stylesheet" href="{% static 'dashboard/css/responsive.css' %}" />
      <!-- color css -->
      <link rel="stylesheet" href="{% static 'dashboard/css/colors.css' %}" />
      <!-- select bootstrap -->
      <link rel="stylesheet" href="{% static 'dashboard/css/bootstrap-select.css' %}" />
      <!-- scrollbar css -->
      <link rel="stylesheet" href="{% static 'dashboard/css/perfect-scrollbar.css' %}" />
      <!-- custom css -->
      <link rel="stylesheet" href="{% static 'dashboard/css/custom.css' %}" />
      <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
      <![endif]-->
   </head>
   <body class="inner_page profile_page">
      <div class="full_container">
         <div class="inner_container">
            <!-- Sidebar  -->
            <nav id="sidebar">
               <div class="sidebar_blog_1">
                  <div class="sidebar-header">
                     <div class="logo_section">
                        <a href="{% url 'dashboard:index' %}"><img class="logo_icon img-responsive" src="{% static 'dashboard/images/logo/logo_icon.png' %}" alt="#" /></a>
                     </div>
                  </div>
                  <div class="sidebar_user_info">
                     <div class="icon_setting"></div>
                     <div class="user_profle_side">
                        <div class="user_img"><img class="img-responsive" src="{% static 'dashboard/images/layout_img/user_img.jpg' %}" alt="#" /></div>
                        <div class="user_info">
                           <h6>John David</h6>
                           <p><span class="online_animation"></span> Online</p>
                        </div>
                     </div>
                  </div>
               </div>
               <div class="sidebar_blog_2">
                  <h4>General</h4>
                  <ul class="list-unstyled components">
                     <li class="active">
                        <a href="#dashboard" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle"><i class="fa fa-dashboard yellow_color"></i> <span>Dashboard</span></a>
                     </li>
                     <li>
                        <a href="#element" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle"><i class="fa fa-diamond purple_color"></i> <span>Elements</span></a>
                     </li>
                     <li><a href="{% url 'dashboard:tables' %}"><i class="fa fa-table purple_color2"></i> <span>Tables</span></a></li>
                     <li>
                        <a href="#apps" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle"><i class="fa fa-object-group blue2_color"></i> <span>Apps</span></a>
                        <ul class="collapse list-unstyled" id="apps">
                           <li><a href="{% url 'dashboard:email' %}">> <span>Email</span></a></li>
                           <li><a href="{% url 'dashboard:media' %}">> <span>Media Gallery</span></a></li>
                        </ul>
                     </li>
                     <li>
                        <a href="{% url 'dashboard:contact' %}">
                        <i class="fa fa-paper-plane red_color"></i> <span>Contact</span></a>
                     </li>
                     <li class="active">
                        <a href="#additional_page" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle"><i class="fa fa-clone yellow_color"></i> <span>Additional Pages</span></a>
                        <ul class="collapse list-unstyled" id="additional_page">
                           <li>
                              <a href="{% url 'dashboard:profile' %}">> <span>Profile</span></a>
                           </li>
                           <li>
                              <a href="{% url 'dashboard:login' %}">> <span>Login</span></a>
                           </li>
                        </ul>
                     </li>
                  </ul>
               </div>
            </nav>
            <!-- end sidebar -->
            <!-- right content -->
            <div id="content">
               <!-- topbar -->
               <div class="topbar">
                  <nav class="navbar navbar-expand-lg navbar-light">
                     <div class="full">
                        <button type="button" id="sidebarCollapse" class="sidebar_toggle"><i class="fa fa-bars"></i></button>
                        <div class="logo_section">
                           <a href="{% url 'dashboard:index' %}"><img class="img-responsive" src="{% static 'dashboard/images/logo/logo.png' %}" alt="#" /></a>
                        </div>
                        <div class="right_topbar">
                           <div class="icon_info">
                              <ul>
                                 <li><a href="#"><i class="fa fa-bell-o"></i><span class="badge">2</span></a></li>
                                 <li><a href="#"><i class="fa fa-question-circle"></i></a></li>
                                 <li><a href="#"><i class="fa fa-envelope-o"></i><span class="badge">3</span></a></li>
                              </ul>
                              <ul class="user_profile_dd">
                                 <li>
                                    <a class="dropdown-toggle" data-toggle="dropdown"><img class="img-responsive rounded-circle" src="{% static 'dashboard/images/layout_img/user_img.jpg' %}" alt="#" /><span class="name_user">John David</span></a>
                                    <div class="dropdown-menu">
                                       <a class="dropdown-item" href="{% url 'dashboard:profile' %}">My Profile</a>
                                       <a class="dropdown-item" href="#"><span>Log Out</span> <i class="fa fa-sign-out"></i></a>
                                    </div>
                                 </li>
                              </ul>
                           </div>
                        </div>
                     </div>
                  </nav>
               </div>
               <!-- end topbar -->
               <!-- dashboard inner -->
               <div class="midde_cont">

                  <!-- end dashboard inner -->
               </div>
            </div>
         </div>
      </div>
      <!-- jQuery -->
      <script src="{% static 'dashboard/js/jquery.min.js' %}"></script>
      <script src="{% static 'dashboard/js/popper.min.js' %}"></script>
      <script src="{% static 'dashboard/js/bootstrap.min.js' %}"></script>
      <!-- wow animation -->
      <script src="{% static 'dashboard/js/animate.js' %}"></script>
      <!-- select country -->
      <script src="{% static 'dashboard/js/bootstrap-select.js' %}"></script>
      <!-- owl carousel -->
      <script src="{% static 'dashboard/js/owl.carousel.js' %}"></script> 
      <!-- chart js -->
      <script src="{% static 'dashboard/js/Chart.min.js' %}"></script>
      <script src="{% static 'dashboard/js/Chart.bundle.min.js' %}"></script>
      <script src="{% static 'dashboard/js/utils.js' %}"></script>
      <script src="{% static 'dashboard/js/analyser.js' %}"></script>
      <!-- nice scrollbar -->
      <script src="{% static 'dashboard/js/perfect-scrollbar.min.js' %}"></script>
      <script>
         var ps = new PerfectScrollbar('#sidebar');
      </script>
      <!-- custom js -->
      <script src="{% static 'dashboard/js/custom.js' %}"></script>
      <!-- calendar file css -->    
      <script src="{% static 'dashboard/js/semantic.min.js' %}"></script>
   </body>
</html>